services:
  synctv:
    image: synctvorg/synctv:latest
    container_name: synctv
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - "../files/synctv/data:/root/.synctv"
    expose:
      - 8080
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      - traefik.enable=true
      - traefik.http.routers.synctv-app.rule=Host(`m.hweb.peterchen97.cn`)

      - "traefik.http.services.synctv.loadbalancer.server.port=8080"
      - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true
