services:
  synctv:
    image: synctvorg/synctv:latest
    container_name: synctv
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - "../files/synctv/data:/root/.synctv"
    expose:
      - 8080
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  dokploy-network:
    external: true
