services:
  synctv:
    image: synctvorg/synctv:latest
    container_name: synctv
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - "../files/synctv/data:/root/.synctv"
    expose:
      - 8080
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
